### ISSUE TITLE
Upgrade to 0.8.5 results in invalid memory/nil pointer error

### ISSUE THREAD

**Issue by nhudson** [kube-vip/kube-vip#982]
**Describe the bug**
After the upgrade from `0.8.4` -> `0.8.5` I now get an error when running kube-vip. 

This is running on a Raspberry Pi 5 (8GB) in a k3s cluster.

```
time="2024-10-31T23:40:49Z" level=info msg="Starting kube-vip.io [v0.8.5]"
time="2024-10-31T23:40:49Z" level=info msg="namespace [kube-system], Mode: [ARP], Features(s): Control Plane:[true], Services:[false]"
time="2024-10-31T23:40:49Z" level=info msg="No interface is specified for VIP in config, auto-detecting default Interface"
time="2024-10-31T23:40:49Z" level=info msg="prometheus HTTP server started"
time="2024-10-31T23:40:49Z" level=info msg="kube-vip will bind to interface [eth0]"
time="2024-10-31T23:40:49Z" level=warning msg="Node name is missing from the config, fall back to hostname"
time="2024-10-31T23:40:49Z" level=info msg="Using node name [pik8s01]"
time="2024-10-31T23:40:49Z" level=info msg="Starting Kube-vip Manager with the ARP engine"
time="2024-10-31T23:40:49Z" level=info msg="Starting UPNP Port Refresher"
time="2024-10-31T23:40:49Z" level=info msg="Beginning cluster membership, namespace [kube-system], lock name [plndr-cp-lock], id [pik8s01]"
I1031 23:40:49.180672       1 leaderelection.go:250] attempting to acquire leader lease kube-system/plndr-cp-lock...
time="2024-10-31T23:40:49Z" level=info msg="Node [pik8s01] is assuming leadership of the cluster"
I1031 23:40:49.193067       1 leaderelection.go:260] successfully acquired lease kube-system/plndr-cp-lock
time="2024-10-31T23:40:49Z" level=info msg="Starting IPVS LoadBalancer"
time="2024-10-31T23:40:49Z" level=info msg="IPVS Loadbalancer enabled for 1.2.1"
time="2024-10-31T23:40:49Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
time="2024-10-31T23:40:49Z" level=info msg="Gratuitous Arp broadcast will repeat every 3 seconds for [192.168.6.40/eth0]"
E1031 23:40:49.194773       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 26 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x17eafa0, 0x2e59990})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x400061a1c0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/runtime/runtime.go:49 +0x78
panic({0x17eafa0?, 0x2e59990?})
	/usr/local/go/src/runtime/panic.go:785 +0x124
k8s.io/client-go/kubernetes.(*Clientset).CoreV1(...)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/kubernetes/clientset.go:309
github.com/kube-vip/kube-vip/pkg/cluster.(*Manager).NodeWatcher.func1({{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x1, ...})
	/src/pkg/cluster/clusterLeaderElection.go:314 +0x2c
k8s.io/client-go/tools/cache.(*ListWatch).Watch(0x10?, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/cache/listwatch.go:111 +0x48
k8s.io/client-go/tools/watch.(*RetryWatcher).doReceive(0x400052a200)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:102 +0x94
k8s.io/client-go/tools/watch.(*RetryWatcher).receive.func2({0x1e48530, 0x4000414cd0})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:264 +0x3c
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x2c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x400071a570?)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x40006dbe88, {0x1e2bdc0, 0x400071a570}, 0x0, 0x400040a620)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x40006dbe88, 0x3b9aca00, 0x0, 0x0, 0x400040a620)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1e48530, 0x4000414cd0}, 0x40006dbf28, 0x3b9aca00, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x78
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntilWithContext(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:190
k8s.io/client-go/tools/watch.(*RetryWatcher).receive(0x400052a200)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:263 +0x220
created by k8s.io/client-go/tools/watch.newRetryWatcher in goroutine 60
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:84 +0x1a4
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x155bafc]

goroutine 26 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x400061a1c0?})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/runtime/runtime.go:56 +0xe0
panic({0x17eafa0?, 0x2e59990?})
	/usr/local/go/src/runtime/panic.go:785 +0x124
k8s.io/client-go/kubernetes.(*Clientset).CoreV1(...)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/kubernetes/clientset.go:309
github.com/kube-vip/kube-vip/pkg/cluster.(*Manager).NodeWatcher.func1({{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x1, ...})
	/src/pkg/cluster/clusterLeaderElection.go:314 +0x2c
k8s.io/client-go/tools/cache.(*ListWatch).Watch(0x10?, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/cache/listwatch.go:111 +0x48
k8s.io/client-go/tools/watch.(*RetryWatcher).doReceive(0x400052a200)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:102 +0x94
k8s.io/client-go/tools/watch.(*RetryWatcher).receive.func2({0x1e48530, 0x4000414cd0})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:264 +0x3c
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x2c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x400071a570?)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x40006dbe88, {0x1e2bdc0, 0x400071a570}, 0x0, 0x400040a620)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x40006dbe88, 0x3b9aca00, 0x0, 0x0, 0x400040a620)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1e48530, 0x4000414cd0}, 0x40006dbf28, 0x3b9aca00, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x78
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntilWithContext(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:190
k8s.io/client-go/tools/watch.(*RetryWatcher).receive(0x400052a200)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:263 +0x220
created by k8s.io/client-go/tools/watch.newRetryWatcher in goroutine 60
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:84 +0x1a4
```

**To Reproduce**
1: Upgrade from `0.8.4` to `0.8.5`
2: Observe Pod status
3: View logs

**Expected behavior**
I would have expected the upgrade to start normally after the version upgrade.

**Screenshots**

**Environment (please complete the following information):**
 - OS/Distro: Debian 12 Bookworm
 - Kubernetes Version: 1.31.1-k3s
 - Kube-vip Version: 0.8.5

**Additional context**
Here are the environment variable I have set in the `DaemonSet`

```
        env:
        - name: address
          value: 192.168.6.40
        - name: vip_arp
          value: "true"
        - name: lb_enable
          value: "true"
        - name: port
          value: "6443"
        - name: vip_cidr
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: kube-system
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "15"
        - name: vip_renewdeadline
          value: "10"
        - name: vip_retryperiod
          value: "2"
        - name: prometheus_server
          value: :2112
```

**Comment by Cellebyte** [comment]
@nhudson could you try this image?

```
ghcr.io/cellebyte/kube-vip:v0.8.5-hotfix.0
```
or you can wait for the nightly build of the `main` branch.

**Comment by nhudson** [comment]
> @nhudson could you try this image?
> 
> ```
> ghcr.io/cellebyte/kube-vip:v0.8.5-hotfix.0
> ```
> 
> or you can wait for the nightly build of the `main` branch.

```
kubectl get ds -n kube-system kube-vip -oyaml | grep image:
        image: ghcr.io/cellebyte/kube-vip:v0.8.5-hotfix.0
```

Thanks!  Looks like it's the same error

```
time="2024-11-01T20:24:16Z" level=info msg="Kube-Vip is watching nodes for control-plane labels"
E1101 20:24:16.707627       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 42 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x17eafa0, 0x2e59990})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x400014a380?})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/runtime/runtime.go:49 +0x78
panic({0x17eafa0?, 0x2e59990?})
	/usr/local/go/src/runtime/panic.go:785 +0x124
k8s.io/client-go/kubernetes.(*Clientset).CoreV1(...)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/kubernetes/clientset.go:309
github.com/kube-vip/kube-vip/pkg/cluster.(*Manager).NodeWatcher.func1({{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x1, ...})
	/src/pkg/cluster/clusterLeaderElection.go:318 +0x2c
k8s.io/client-go/tools/cache.(*ListWatch).Watch(0x0?, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/cache/listwatch.go:111 +0x48
k8s.io/client-go/tools/watch.(*RetryWatcher).doReceive(0x400033dd80)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:102 +0x94
k8s.io/client-go/tools/watch.(*RetryWatcher).receive.func2({0x1e48530, 0x4000640280})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:264 +0x3c
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x2c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4000674060?)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4000600e88, {0x1e2bdc0, 0x4000674060}, 0x0, 0x400064e3f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x400048de88, 0x3b9aca00, 0x0, 0x0, 0x400064e3f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1e48530, 0x4000640280}, 0x400048df28, 0x3b9aca00, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x78
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntilWithContext(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:190
k8s.io/client-go/tools/watch.(*RetryWatcher).receive(0x400033dd80)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:263 +0x220
created by k8s.io/client-go/tools/watch.newRetryWatcher in goroutine 79
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:84 +0x1a4
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x155bafc]

goroutine 42 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x400014a380?})
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/runtime/runtime.go:56 +0xe0
panic({0x17eafa0?, 0x2e59990?})
	/usr/local/go/src/runtime/panic.go:785 +0x124
k8s.io/client-go/kubernetes.(*Clientset).CoreV1(...)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/kubernetes/clientset.go:309
github.com/kube-vip/kube-vip/pkg/cluster.(*Manager).NodeWatcher.func1({{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, 0x1, ...})
	/src/pkg/cluster/clusterLeaderElection.go:318 +0x2c
k8s.io/client-go/tools/cache.(*ListWatch).Watch(0x0?, {{{0x0, 0x0}, {0x0, 0x0}}, {0x0, 0x0}, {0x0, 0x0}, 0x0, ...})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/cache/listwatch.go:111 +0x48
k8s.io/client-go/tools/watch.(*RetryWatcher).doReceive(0x400033dd80)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:102 +0x94
k8s.io/client-go/tools/watch.(*RetryWatcher).receive.func2({0x1e48530, 0x4000640280})
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:264 +0x3c
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x2c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x4000674060?)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x400066be88, {0x1e2bdc0, 0x4000674060}, 0x0, 0x400064e3f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x400048de88, 0x3b9aca00, 0x0, 0x0, 0x400064e3f0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x1e48530, 0x4000640280}, 0x400048df28, 0x3b9aca00, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:259 +0x78
k8s.io/apimachinery/pkg/util/wait.NonSlidingUntilWithContext(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.29.3/pkg/util/wait/backoff.go:190
k8s.io/client-go/tools/watch.(*RetryWatcher).receive(0x400033dd80)
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:263 +0x220
created by k8s.io/client-go/tools/watch.newRetryWatcher in goroutine 79
	/go/pkg/mod/k8s.io/client-go@v0.29.1/tools/watch/retrywatcher.go:84 +0x1a4
```

**Comment by Cellebyte** [comment]
Weird… you run kube-vip as controlplane and service lb provider?

**Comment by Cellebyte** [comment]
@p-strusiewiczsurmacki-mobica could you have a look at that on Monday?

**Comment by nhudson** [comment]
> Weird… you run kube-vip as controlplane and service lb provider?

Currently it's only configured as a ipvs control-plane load balancer.

Here are the environment variables I am using currently when running.

```
    - name: address
      value: 192.168.6.40
    - name: vip_arp
      value: "true"
    - name: lb_enable
      value: "true"
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_ddns
      value: "false"
    - name: svc_enable
      value: "false"
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "15"
    - name: vip_renewdeadline
      value: "10"
    - name: vip_retryperiod
      value: "2"
    - name: prometheus_server
      value: :2112
```

**Comment by Cellebyte** [comment]
@nhudson I want to learn more about the deployment method.

I saw from the reference above, that you use a helm chart.
Could you link the source of the helm chart here as well as a description how the controlplane mode should work in the setup you are using? 

I am not familiar using kube-vip in cp mode without static manifest.

**Comment by nhudson** [comment]
@Cellebyte 

I am not deploying via a Helm chart.  I am just running it as a `DaemonSet` on the control-plane node that is deployed using FluxCD from [here](https://github.com/nhudson/pik8s/blob/main/kubernetes/apps/kube-system/kube-vip/app/daemonset.yaml)

**Comment by Raboo** [comment]
I can confirm I have the same issue, v0.8.4 works well, but not v.0.8.5
Running Ubuntu 24.04 on kernel 6.8.0-48-generic.

**Comment by Cellebyte** [comment]
@Raboo do you also use `lb_enable`?

**Comment by Raboo** [comment]
@Cellebyte yes.
However I just noticed i have "True" instead of "true", not sure if that matters.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi, I've just created PR with fix.

It seems that while adding the RWClient I've missed one point where it should be created, and this part of code is only used when IPVS loadbalancer is being used.

@Cellebyte @nhudson @Raboo

**Comment by Raboo** [comment]
Awesome, happy to test once images gets publicized.

**Comment by Cellebyte** [comment]
@p-strusiewiczsurmacki-mobica thanks :)

**Comment by nhudson** [comment]
@Cellebyte @p-strusiewiczsurmacki-mobica I can confirm that the version pushed today `v0.8.6` works as expected.  Thanks a ton!

**Comment by Cellebyte** [comment]
@nhudson first time doing a release of such a widely used OSS project. Thanks for the patience.

Good Night from Germany ;)
